### ISSUE TITLE
how to get the file rcv1.tar.xz

### ISSUE THREAD

**Issue by SeekPoint** [sld/torch-conv-ner#1]
I find rcv1.tar.gz on the internet
but it is not *.xz,

**Comment by sld** [comment]
You should get and compile CoNLL 2003 corpus.
Steps are described here: http://www.cnts.ua.ac.be/conll2003/ner/.

**Comment by SeekPoint** [comment]
I see the 000README:

NOTE: ADDED 16 AUGUST 2016

The Reuters Corpus is not distributed on a cd anymore but as a single
compressed file rcv1.tar.xz . In order to extract the English shared
task files from this file, you need the script ner/bin/make.eng.2016

1. download ner.tgz from http://www.clips.uantwerpen.be/conll2003/ner/
2. extract the files from ner.tgz: tar zxf ner.tgz
3. put the Reuters file rcv1.tar.xz in the new directory ner
4. run make.eng.2016 from directory ner: cd ner; bin/make.eng.2016

This should generate the three files eng.train, eng.testa and eng.testb

Contact: erikt(at)xs4all.nl


however, i only got  rcv1.tar.gz from internet

would you like share the  rcv1.tar.xz to me?

**Comment by sld** [comment]
Sorry, I haven't that file. 
You may find compiled CoNLL 2003 here: https://github.com/patverga/torch-ner-nlp-from-scratch/tree/master/data/conll2003

**Comment by SeekPoint** [comment]
great

**Comment by SeekPoint** [comment]
how to generate 

    data/conll2003/eng.testa.dev;
    data/conll2003/eng.testb.test;
    data/conll2003/eng.train

in https://github.com/patverga/torch-ner-nlp-from-scratch/tree/master/data/conll2003, I see:
should I rename some file name?

eng.testa 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.testa.index 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.testa.torch 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.testb 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.testb.index 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.testb.torch 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.train 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.train.index 	move around some files, add data to repo cuz fuckit 	a year ago
	eng.train.torch 	move around some files, add data to repo cuz fuckit 	a year ago

**Comment by voyager0003** [comment]
rcv1 is a set of 1393 news of Reuters Press. Which can be download from here https://trec.nist.gov/data/reuters/reuters.html
